### ISSUE TITLE
如何使用

### ISSUE THREAD

**Issue by akikans** [yuzhen1024/quick_speed_toggle#1]
hello！
放到scripts文件夹下并不起作用，需要修改input.conf文档吗

**Comment by yuzhen1024** [comment]
> hello！ 放到scripts文件夹下并不起作用，需要修改input.conf文档吗

不需要。
排查下是什么问题吧。

**Comment by yuzhen1024** [comment]
![Screenshot_20220911_184756](https://user-images.githubusercontent.com/47154428/189523478-4f910f09-61f5-4fa9-90f5-1c0e59aa7706.jpeg)

我当初遇过一个低级错误是拼写错误，`scripts` 写成 `script` 。

**Comment by akikans** [comment]
找到原因：禁用了默认快捷键

**Comment by akikans** [comment]
完成！不要用no-input-default-bindings，用no-input-builtin-bindings就好了。
感谢作者
