### ISSUE TITLE
How to bind two keys?

### ISSUE THREAD

**Issue by isPoto** [yuzhen1024/quick_speed_toggle#2]
I want to bind z and the middle mouse button, but I've tried several ways to write it and it doesn't work. How can I accomplish this?

**Comment by yuzhen1024** [comment]
I updated this script
now juse change this line: https://github.com/yuzhen1024/quick_speed_toggle/blob/c930f9307c8e536c072b97a84fdbb3ca7f8c6433/speedtoggle.lua#L3
`local keys = { "z", "MBTN_MID" }`

**Comment by yuzhen1024** [comment]
If have any other questions, continue asking.
